# Unique name for this workflow
name: Code Style (Prettier)

# Definition when the workflow should run
on: [push]

# Jobs to be executed
jobs:
    formatting-and-linting:
        runs-on: ubuntu-latest
        steps:
            # Checkout the code in the pull request
            - name: "Checkout source code"
              uses: actions/checkout@v2

            - name: "Setup Node.js"
              uses: actions/setup-node@v2.1.1
              with:
                  node-version: "12.x"
            - name: Install dependencies
              run: npm ci

            # Prettier formatting
            - name: "Code formatting verification with Prettier"
              run: npm run prettier:verify

            # Lint LWC
            - name: "Lint Lightning Web Components"
              run: npm run lint:lwc
